name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Déclenche l'action sur chaque push vers la branche principale

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Vérification du code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Exécuter des tests (exemple avec npm)
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Cette étape attend que les tests réussissent
    steps:
      # Étape 1 : Vérification du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Déploiement à Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1
        with:
          auth_token: ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Token d'authentification de Netlify
          site_id: ${{ secrets.NETLIFY_SITE_ID }}        # Identifiant du site Netlify
          dir: ./build                                   # Répertoire où se trouve le build de l'application
